
name: "Terraform Plan"

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: "Terraform Init & Plan"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./environments/dev

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Formatage du code
        run: terraform fmt -check -recursive ../..

      - name: Initialisation Terraform
        run: terraform init -backend=false

      - name: Validation du code HCL
        run: terraform validate